server:
  port: 8763
eureka:
  client:
    service-url:
      #指定位置像哪里注册
      defaultZone:  http://localhost:8761/eureka,http://localhost:8762/eureka
    register-with-eureka: false
    fetch-registry: false
  server:
    #关闭自自保模式
#    enable-self-preservation: false
    #超时多长时间后 剔除eureka实例默认60*1000
    eviction-interval-timer-in-ms: 3000


spring:
  application:
    name: EUREKASERVER




