server:
  port: 8001
spring:
  application:
    name: EUREKACLIENTDEMO

eureka:
   client:
     service-url:
       #填写所有节点 保证某一注册中心down机能继续注册进来
       defaultZone:  http://localhost:8761/eureka,http://localhost:8762/eureka,http://localhost:8761/eureka
   instance:
     lease-expiration-duration-in-seconds: 10
     lease-renewal-interval-in-seconds: 5